import { prepareBookingDialog } from "./confirmation";
import {
  timezoneLabel,
  displayBookingDateTime,
  displayPhone,
  renderBookingSummary,
} from "./presentation";
import {
  bookingTokenSchema,
  bookingInputSchema,
  type PublicBooking,
  type PublicBookingPage,
  type BookingSlot,
} from "./contract";
export async function setupPublicBooking() {
  const root = document.querySelector<HTMLElement>("[data-public-booking]");
  if (!root) return;
  const el = <T extends HTMLElement = HTMLElement>(s: string) =>
    root.querySelector<T>(s)!;
  const form = el<HTMLFormElement>("[data-public-booking-form]"),
    dialog = el<HTMLDialogElement>("[data-booking-confirm]"),
    feedback = el("[data-booking-feedback]");
  prepareBookingDialog(dialog);
  let page: PublicBookingPage,
    selected: BookingSlot | null = null,
    busy = false,
    mode: "book" | "reschedule" | "cancel" = "book",
    slotsVersion = 0,
    requestKey = crypto.randomUUID();
  const field = <
    T extends HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement =
      HTMLInputElement,
  >(
    name: string,
  ) => form.elements.namedItem(name) as T;
  const token = bookingTokenSchema.safeParse(
    location.pathname.split("/").filter(Boolean)[1],
  );
  if (!token.success) {
    feedback.textContent = "This booking link is unavailable.";
    feedback.setAttribute("role", "alert");
    return;
  }
  const url = "/api/booking?token=" + encodeURIComponent(token.data),
    announce = (value: string, error = false) => {
      feedback.textContent = value;
      feedback.setAttribute("role", error ? "alert" : "status");
    };
  async function request<T>(options: RequestInit = {}, extra = ""): Promise<T> {
    const r = await fetch(url + extra, {
        ...options,
        credentials: "omit",
        cache: "no-store",
        signal: AbortSignal.timeout(20000),
      }),
      body = await r.json();
    if (!r.ok)
      throw Error(
        typeof body.error === "string"
          ? body.error
          : "Booking could not be confirmed.",
      );
    return body as T;
  }
  field("clientEmail").readOnly = true;
  function validation(errors: Record<string, string>) {
    form.querySelectorAll<HTMLElement>("[data-field-error]").forEach((node) => {
      node.textContent = errors[node.dataset.fieldError!] ?? "";
      node.hidden = !node.textContent;
    });
    form
      .querySelectorAll<
        HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
      >("input,textarea,select")
      .forEach((input) =>
        errors[input.name]
          ? input.setAttribute("aria-invalid", "true")
          : input.removeAttribute("aria-invalid"),
      );
    form.querySelector<HTMLElement>("[aria-invalid]")?.focus();
  }
  const buttonLabel = (selector: string, label: string) =>
    el(selector)
      .querySelectorAll<HTMLElement>(
        ".ui-button-text-default,.ui-button-text-hover",
      )
      .forEach((span) => (span.textContent = label));
  function confirmLabel() {
    el('[id="booking-confirm-heading"]').textContent =
      mode === "cancel"
        ? "Cancel your booking?"
        : mode === "reschedule"
          ? "Confirm your new time"
          : "Confirm your booking";
    buttonLabel(
      "[data-booking-confirm-save]",
      mode === "cancel"
        ? "Cancel booking"
        : mode === "reschedule"
          ? "Confirm new time"
          : "Confirm booking",
    );
  }
  function meeting() {
    const type = (form.elements.namedItem("meetingType") as RadioNodeList)
      .value;
    el("[data-booking-phone]").hidden = type === "zoom";
    field("clientPhone").required = type === "phone";
    el("[data-meeting-hint]").textContent =
      type === "zoom"
        ? "Your Zoom meeting link will be provided separately. No Zoom link is generated by this booking."
        : "A phone number is required for a phone call.";
  }
  function render() {
    field("clientName").value = field("clientName").value || page.name;
    field("clientEmail").value = page.email;
    el("[data-booking-timezone]").textContent =
      `Times in ${timezoneLabel(page.timezone)} / ${page.durationMinutes}-minute calls`;
    const date = field<HTMLSelectElement>("bookingDate"),
      value = date.value;
    date.replaceChildren(
      new Option("Choose an available date", ""),
      ...page.dates.map((d) => new Option(d.label, d.date)),
    );
    date.value = page.dates.some((d) => d.date === value) ? value : "";
    el("[data-existing-booking]").hidden = !page.booking;
    if (page.booking) {
      const b = page.booking;
      renderBookingSummary(el("[data-existing-summary]"), b);
      el("[data-existing-meeting]").textContent =
        b.status === "cancelled"
          ? "This call has been cancelled."
          : b.status === "completed"
            ? "This call is complete."
            : b.meetingType === "zoom"
              ? "A Zoom link will be provided separately."
              : "We’ll call " + displayPhone(b.clientPhone ?? "") + ".";
      el("[data-existing-actions]").hidden =
        b.status !== "scheduled" || Date.parse(b.startAt) <= Date.now();
    }
    form.hidden = page.booking?.status === "scheduled";
    if (!page.dates.length && page.booking?.status !== "scheduled") {
      form.hidden = true;
      announce(
        "No times are currently available. Please check again later or contact Volatile Solutions.",
      );
    } else
      announce(
        page.booking?.status === "scheduled"
          ? "Your call is scheduled."
          : "Choose your call and time.",
      );
    meeting();
  }
  async function loadSlots() {
    selected = null;
    const version = ++slotsVersion,
      container = el("[data-booking-slots]");
    container.replaceChildren();
    el("[data-booking-slot-error]").hidden = true;
    if (!field("bookingDate").value) return;
    container.setAttribute("aria-busy", "true");
    try {
      const data = await request<{ slots: BookingSlot[] }>(
        {},
        "&date=" + encodeURIComponent(field("bookingDate").value),
      );
      if (version !== slotsVersion) return;
      el("[data-slots-empty]").hidden = data.slots.length > 0;
      for (const slot of data.slots) {
        const fragment = el<HTMLTemplateElement>(
          "[data-booking-slot-template]",
        ).content.cloneNode(true) as DocumentFragment;
        const button = fragment.querySelector<HTMLButtonElement>("button")!;
        button
          .querySelectorAll<HTMLElement>(
            ".ui-button-text-default,.ui-button-text-hover",
          )
          .forEach((span) => (span.textContent = slot.label));
        button.setAttribute("aria-label", slot.label);
        button.setAttribute("aria-pressed", "false");
        button.setAttribute("aria-describedby", "booking-slot-error");
        button.addEventListener("click", () => {
          selected = slot;
          container
            .querySelectorAll("button")
            .forEach((b) =>
              b.setAttribute("aria-pressed", String(b === button)),
            );
          el("[data-booking-slot-error]").hidden = true;
        });
        container.append(fragment);
      }
    } catch (error) {
      if (version === slotsVersion)
        announce(
          error instanceof Error ? error.message : "Times could not be loaded.",
          true,
        );
    } finally {
      if (version === slotsVersion) container.removeAttribute("aria-busy");
    }
  }
  async function refresh() {
    page = await request<PublicBookingPage>();
    render();
  }
  try {
    await refresh();
  } catch (error) {
    announce(
      error instanceof Error
        ? error.message
        : "This booking link is unavailable.",
      true,
    );
    return;
  }
  field("bookingDate").addEventListener("change", () => {
    void loadSlots();
  });
  form
    .querySelectorAll('[name="meetingType"]')
    .forEach((r) => r.addEventListener("change", meeting));
  form.addEventListener("submit", (event) => {
    event.preventDefault();
    if (busy) return;
    if (!selected) {
      el("[data-booking-slot-error]").textContent = "Choose an available time.";
      el("[data-booking-slot-error]").hidden = false;
      field("bookingDate").focus();
      return;
    }
    if (page.booking?.status === "scheduled") {
      mode = "reschedule";
      el("[data-booking-confirm-copy]").textContent =
        "Move your call to " +
        displayBookingDateTime(selected.startAt, page.timezone) +
        "?";
      confirmLabel();
      dialog.showModal();
      return;
    }
    const r = bookingInputSchema.safeParse({
      action: "book",
      meetingType: (form.elements.namedItem("meetingType") as RadioNodeList)
        .value,
      startAt: selected.startAt,
      clientName: field("clientName").value,
      clientEmail: field("clientEmail").value,
      clientPhone: field("clientPhone").value,
      clientNotes: field("clientNotes").value,
      requestKey,
      confirmed: true,
    });
    if (!r.success) {
      validation(
        Object.fromEntries(
          r.error.issues.map((i) => [String(i.path[0]), i.message]),
        ),
      );
      return;
    }
    validation({});
    mode = "book";
    el("[data-booking-confirm-copy]").textContent =
      "Book a " +
      r.data.meetingType +
      " call for " +
      displayBookingDateTime(selected.startAt, page.timezone) +
      "?";
    confirmLabel();
    dialog.showModal();
  });
  el("[data-booking-confirm-back]").addEventListener("click", () =>
    dialog.close(),
  );
  el("[data-public-cancel]").addEventListener("click", () => {
    mode = "cancel";
    el("[data-booking-confirm-copy]").textContent =
      "Cancel your scheduled call? This time will become available again.";
    confirmLabel();
    dialog.showModal();
  });
  el("[data-public-reschedule]").addEventListener("click", () => {
    mode = "reschedule";
    form.hidden = false;
    form.querySelectorAll("fieldset").forEach((f, index) => {
      f.hidden = index !== 1;
    });
    buttonLabel("[data-booking-review]", "Review new time");
    field("bookingDate").focus();
  });
  el("[data-booking-confirm-save]").addEventListener("click", async () => {
    if (busy) return;
    busy = true;
    root.setAttribute("aria-busy", "true");
    dialog.close();
    root
      .querySelectorAll<
        | HTMLButtonElement
        | HTMLInputElement
        | HTMLSelectElement
        | HTMLTextAreaElement
      >("button,input,select,textarea")
      .forEach((b) => (b.disabled = true));
    announce("Saving your booking…");
    try {
      const body =
        mode === "book"
          ? {
              action: "book",
              meetingType: (
                form.elements.namedItem("meetingType") as RadioNodeList
              ).value,
              startAt: selected!.startAt,
              clientName: field("clientName").value,
              clientEmail: field("clientEmail").value,
              clientPhone: field("clientPhone").value,
              clientNotes: field("clientNotes").value,
              requestKey,
              confirmed: true,
            }
          : {
              action: mode,
              expectedStartAt: page.booking!.startAt,
              ...(mode === "reschedule" ? { startAt: selected!.startAt } : {}),
              confirmed: true,
            };
      const result = await request<{ booking: PublicBooking }>({
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      page.booking = result.booking;
      await refresh();
      form.querySelectorAll("fieldset").forEach((f) => (f.hidden = false));
      mode = "book";
      buttonLabel("[data-booking-review]", "Review booking");
      requestKey = crypto.randomUUID();
      announce(
        result.booking.status === "cancelled"
          ? "Your booking was cancelled."
          : "Your booking is confirmed.",
      );
      el('[id="existing-booking-heading"]')?.focus();
    } catch (error) {
      const text =
        error instanceof Error
          ? error.message
          : "Booking could not be confirmed. Your details are preserved.";
      try {
        await refresh();
      } catch {}
      announce(text, true);
    } finally {
      busy = false;
      root.removeAttribute("aria-busy");
      root
        .querySelectorAll<
          | HTMLButtonElement
          | HTMLInputElement
          | HTMLSelectElement
          | HTMLTextAreaElement
        >("button,input,select,textarea")
        .forEach((b) => (b.disabled = false));
      feedback.tabIndex = -1;
      feedback.focus();
    }
  });
}
